First
MilaSnetkova/TODO-list pull request #1
Opened 2024-10-15 07:53 UTC by MilaSnetkova

2024-10-15 23:06 UTC, dirtymew requested changes
Привет Людмила

очень хорошая работа, хочется отметить
 - архитектуру и структуру решения
 - задания со звездочкой
 - тесты все проходят
 - в целом чистый код
 - использование интерфейсов

дал комментарии что поправить и улучшить, критичных замечаний мало - исправляй и в целом готов принять работу

2024-10-15 23:06 UTC, dirtymew commented on .env
> +JWT_SECRET=your_secure_jwt_secret
все переменные для приложения стоит с префиксом TODO_ обьявить

2024-10-15 23:06 UTC, dirtymew commented on internal/config/config.go
> +	Timeout       time.Duration `env:"TIMEOUT" env-default:"5s"`
а зачем Ticker и Timeout?

2024-10-15 23:06 UTC, dirtymew commented on internal/auth/auth.go
> +		currentPassword := os.Getenv("TODO_PASSWORD")
это не очень хорошо делать в хендлерах - нужно поправить

запросы к os это очень накладно - стоит один раз конфигурацию прочитать на старте приложения

2024-10-15 23:06 UTC, dirtymew commented on internal/db/db.go
> +	DB, err = sqlx.Open("sqlite3", dbPath)
тут не очень понятно 

ты присваиваешь значение к глобальной переменной и потом ее же и возвращаешь...

мб не нужна глобальная перменная вообще?

2024-10-15 23:06 UTC, dirtymew commented on internal/constants/constants.go
> +Lim = 50
Limit

2024-10-15 23:06 UTC, dirtymew commented on internal/repository/repository.go
> +	GetTaskByID(id string) (*models.Task, error)
кажется что можно SearchTasks(filter Filter) покрыти и GetTaskByID(id string) ... - это как совет

2024-10-15 23:06 UTC, dirtymew commented on internal/repository/repository.go
> +	UpdateTaskDate(id string, newDate string) error
кажется что UpdateTask(task *models.Task) error достаточно... - тоже совет

2024-10-15 23:06 UTC, dirtymew commented on internal/service/service.go
> +type TaskSer interface {
TaskService - не нужно сокращать имена так

2024-10-15 23:06 UTC, dirtymew commented on internal/repository/repository.go
> +	DoneTask(id string, completedAt time.Time) error
кажется что это не логика хранилища - а сервиса и там можно всю логику описать

2024-10-15 23:06 UTC, dirtymew commented on internal/repository/repository.go
> +func (r *TaskRepo) DoneTask(id string, now time.Time) error {
лучше эту логику на уровень сервиса перенести

2024-10-15 23:06 UTC, dirtymew commented on internal/service/service.go
> +func (s *TaskService) TaskDone(id string, now time.Time) error {
а вот тут верно - получается что метод в repo  все-таки не нужен

2024-10-15 23:06 UTC, dirtymew commented on main.go
> +	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
это что странное - стоит убрать 

если хочется gracefull shutdown - то это задача не простая и далеко за рамками курса

https://www.rudderstack.com/blog/implementing-graceful-shutdown-in-go/

2024-10-15 23:06 UTC, dirtymew commented on main.go
> +		defer os.Exit(1)
кажется что тоже лишнее

2024-10-15 23:06 UTC, dirtymew commented on main.go
> +		defer os.Exit(1)
ни в целом странное...

2024-10-16 15:58 UTC, MilaSnetkova commented on internal/config/config.go
> +	Timeout       time.Duration `env:"TIMEOUT" env-default:"5s"`
Поняла, тут не очень нужны они. Убрала

2024-10-16 15:58 UTC, MilaSnetkova commented on internal/auth/auth.go
> +		currentPassword := os.Getenv("TODO_PASSWORD")
Внесла изменения в коммите -final

2024-10-16 15:59 UTC, MilaSnetkova commented on internal/db/db.go
> +	DB, err = sqlx.Open("sqlite3", dbPath)
Изменила

2024-10-16 16:02 UTC, MilaSnetkova commented on main.go
> +	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
Да, хотела shutdown использовать, но не решилась. Переделывала, в main не все изменила (забыла).

2024-10-16 22:42 UTC, dirtymew requested changes
Привет Людмила

сломались тесты и на фронте не работает редактирование задачи

нужно поправить

2024-10-16 22:42 UTC, dirtymew commented on internal/repository/repository.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler WHERE 1=1"
тут не очень понимаю как работает фильтр по id

я бы предложил упростить

напиши нескольо условий - будет проще

2024-10-16 22:42 UTC, dirtymew commented on internal/repository/repository.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler WHERE 1=1"
кажется что получение по id сломалось

2024-10-17 09:37 UTC, MilaSnetkova commented
Теперь все ОК с тестами.

2024-10-17 17:12 UTC, dirtymew approved these changes
Привет Людмила

задание принято

поздравляю и желаю удачи

2024-10-17 17:12 UTC, dirtymew commented on internal/repository/repository.go
> +func (r *TaskRepo) SearchTasks(filter Filter, id string) ([]models.Task, error) {
ну а зачем доп параметр то.. есть же в фильтре ID )

2024-10-17 17:12 UTC, dirtymew commented on internal/repository/repository.go
> +	if id != "" {
можно так было 

```
if len(filter.ID) > 0 {

    ... и тут сделать запрос с операторм IN
}
``

2024-10-18 10:59 UTC, merged